### ISSUE TITLE
not a valid add-on repository

### ISSUE THREAD

**Issue by bacardiiii** [megakid/ha_octopus_intelligent#10]
Trying to add this via HACS I get this 

[GitHub - megakid/ha_octopus_intelligent](https://github.com/megakid/ha_octopus_intelligent) is not a valid add-on repository

**Comment by drnichols** [comment]
I added to HACS tonight using https://github.com/megakid/ha_octopus_intelligent without issue, did you select type = integration?

**Comment by bacardiiii** [comment]
I did but it kept failing. I’ll try again when I’m back over the weekend.CheersRichardOn 8 Dec 2022, at 21:42, drnichols ***@***.***> wrote:﻿
I added to HACS tonight using https://github.com/megakid/ha_octopus_intelligent without issue, did you select type = integration?

**Comment by bacardiiii** [comment]
It appears my sd card was faulty. I’ve now added it 

Thanks
