### ISSUE TITLE
OHME Charger control

### ISSUE THREAD

**Issue by newbuilder22** [megakid/ha_octopus_intelligent#15]
Hi, just double checking that this is by design rather than a bug: 

When changing Target Ready Time, Target % or Boost/immediate charge button, it will not work with OHME chargers as point of OE control as the stream is one way from Ohme to OE?????

Thanks

**Comment by andyvee69** [comment]
There is little point using this (or any other) integration with the Ohme/IO integration as it works very differently. Any plannedDispatches you see are not necessarily when Ohme/Octopus will charge. And the plannedDispatches are removed at just before 17:00 most days anyway. You are correct, the target times and % are not used for the Ohme integration as charge control is via the Ohme app, not the Octopus API.

**Comment by newbuilder22** [comment]
So it will not show "ON" when the feed is sent through for a dispatch? I currently use a CT clamp to sense power pull and then HA adapts accordingly.

**Comment by andyvee69** [comment]
No. As the Ohme integration doesn't work like that. The Octopus API, plannedDispatches and all these various HA integrations are effectively of zero use for the Ohme/IO integration. All you get to see is a superset of times that Ohme/Octopus will schedule your charge within. And unless you cache the plannedDispatches, it all disappears from the API just before 17:00.

**Comment by newbuilder22** [comment]
Advice given
