### ISSUE TITLE
await error in the logs

### ISSUE THREAD

**Issue by ColinRobbins** [megakid/ha_octopus_intelligent#28]
When running the integration, I see the following error in the logs.

```
Logger: py.warnings
Source: runner.py:188
First occurred: 09:36:56 (1 occurrences)
Last logged: 09:36:56

/usr/local/lib/python3.11/asyncio/base_events.py:1910: RuntimeWarning: coroutine 'OctopusIntelligentSystem.start' was never awaited handle = self._ready.popleft()
```

It all seems to work fine, but a sign that the logic is not quite right.

**Comment by megakid** [comment]
Hopefully this is fixed with https://github.com/megakid/ha_octopus_intelligent/releases/tag/v1.6.3
