### ISSUE TITLE
Entity "Octopus Intelligent Off-Peak End" is unknown. 

### ISSUE THREAD

**Issue by snu-snu-snu** [megakid/ha_octopus_intelligent#29]
I run the automation which changes solar inverter work mode based on the IO off-peak on or off. but last few days I noticed that while automation segment which uses the "IO Tariff ON "works as it should, the segment with "IO Tariff OFF" is not working.

From the logs:

```
December 5, 2023
Octopus Bump Charge turned off
9:14:26 AM - 2 hours ago
Octopus Target Ready By Time changed to 06:30
9:14:26 AM - 2 hours ago
Octopus Intelligent Offpeak End became unknown
9:14:25 AM - 2 hours ago
Octopus Intelligent Next Offpeak Start changed to December 5, 2023 at 11:30 PM
9:14:25 AM - 2 hours ago
```
Can it be some changes in the api/entities? can you please check on it/update?

**Comment by megakid** [comment]
Hopefully this is fixed with https://github.com/megakid/ha_octopus_intelligent/releases/tag/v1.6.3
