### ISSUE TITLE
"Intelligent Planned Dispatch Slot" is always "Off"

### ISSUE THREAD

**Issue by MarkTarry** [megakid/ha_octopus_intelligent#32]
I've had this integration installed since 13th Jan '24, and I've noticed that the `Intelligent Planned Dispatch Slot` binary sensor has never changed to an "on" state:
![image](https://github.com/megakid/ha_octopus_intelligent/assets/155492324/ed2f615f-2a5a-4df1-9304-9871d9176664)

While the other sensors are correctly working from my "cheap energy" window of 23:30 - 05:30, I am unable to see when Octopus actually wants to charge my car.

📓 This could be a duplicate of https://github.com/megakid/ha_octopus_intelligent/issues/31, it's not entirely clear from the description of that issue.

**Comment by megakid** [comment]
Hopefully this is fixed with https://github.com/megakid/ha_octopus_intelligent/releases/tag/v1.6.3
