### ISSUE TITLE
Get Octopus Charging Slots

### ISSUE THREAD

**Issue by JasSmiths** [megakid/ha_octopus_intelligent#8]
Hey James, 

Is there a way for you to get the charging times that octopus set for the car and have it setup as a binary_sensor? 

Reason being, this would allow me to set my Zappi charger to allow fast charging during those time slots rather than just a blanket 11:30pm - 5:30am?

Not a big deal if not as having this integration is 100x better than without it, huge appreciation for you creating it.

@megakid

**Comment by megakid** [comment]
Hmm if I understand your question, then this is exactly what this integration does already!

If Octopus schedule your car to charge at 9am for 1 hr, the binary sensor "octopus_intelligent_slot" will be on for that hour.

**Comment by JasSmiths** [comment]
My understanding of how it works (I could definitely be wrong here) is that "octopus_intelligent_slot" will turn on from 11:30pm - 5:30am every day as that would be an off peak time (correctly so).

What I'm trying to achieve is setting my charger to enable fast charging only during the slots octopus set rather than the whole 11:30pm to 5:30am window.

This might be a little outside the usual use case, and I have just found the planned dispatches in the attributes so I should be able to use that, but it would be great if you could add an entity with those times in it, people could then easily use it as an automation trigger

**Comment by JasSmiths** [comment]
Thanks for this
